name: 'Clio install'
description: 'Push package to target'
inputs:
  folder: 
    description: 'Folder to install'
    required: true
  url:
    description: 'Destination url'
    required: true
  login:
    description: 'Destination username'
    required: true
    default: 'Supervisor'
  password:
    description: 'Destination password'
    required: true
    default: 'Supervisor'
runs: 
  using: "composite"
  steps:
    - name: Build before deploy
      shell: powershell
      run: dotnet build ${{ inputs.folder }}\${{ inputs.folder }}.csproj;
    - name: Install Clio tool
      shell: powershell
      run: dotnet tool install clio --tool-path .\ClioTool;
    - name: Install package
      shell: powershell
      run: .\ClioTool\clio.exe install ${{ inputs.folder }} -u ${{ inputs.url }} -l ${{ inputs.login }} -p ${{ inputs.password }};
    - name: Restart application
      shell: powershell
      run: .\ClioTool\clio.exe restart -u ${{ inputs.url }} -l ${{ inputs.login }} -p ${{ inputs.password }};
    - name: Clean Redis
      shell: powershell
      run: .\ClioTool\clio.exe flushdb -u ${{ inputs.url }} -l ${{ inputs.login }} -p ${{ inputs.password }};